### ISSUE TITLE
Add support for ENV variables

### ISSUE THREAD

**Issue by kevinfarrugia** [unsplash/comment-on-pr#23]
As a user I would like to be able to add variables to the commit message.

Example:

```
- name: Comment on PR
  uses: unsplash/comment-on-pr@master
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    VARIABLE: "Foo"
  with:
    msg: "Check out this message $VARIABLE!"
    check_for_duplicate_msg: false
```

**Comment by kevinfarrugia** [comment]
I have managed to workaround using

```
- name: Comment on PR
  uses: unsplash/comment-on-pr@master
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    VARIABLE: "Foo"
  with:
    msg: ${{ 'Check out this message' + env.VARIABLE }}
    check_for_duplicate_msg: false
```
