### ISSUE TITLE
When using parameter check_for_duplicate_msg, a warning is thrown by Github Actions

### ISSUE THREAD

**Issue by fbontin** [unsplash/comment-on-pr#35]
Hi! 

When using this action with the optional parameter `check_for_duplicate_msg`, Github Actions logs a warning (see screenshot below).

Code:
```
- name: Post comment
  uses: unsplash/comment-on-pr@master
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    check_for_duplicate_msg: true
    msg: Hello
```

Screenshot:
![image](https://user-images.githubusercontent.com/7226476/105722289-cba5c700-5f25-11eb-8b12-4648306b8f13.png)
