### ISSUE TITLE
"Couldn't find an open pull request for branch with head at ."

### ISSUE THREAD

**Issue by hughgrigg** [unsplash/comment-on-pr#8]
Getting this error from `unsplash/comment-on-pr@master`:

```
Couldn't find an open pull request for branch with head at .
##[error]Docker run failed with exit code 1
```

The step trying to use `comment-on-pr` looka like this:

```
- uses: actions/checkout@v1
- name: Comment on zero test changes
        uses: unsplash/comment-on-pr@master
        if: steps.file_counts.outputs.test_file_count == 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: >
            @${{ github.actor }}
            Please add tests.
```
